Document: freeplane-flash-browser
Title: Debian freeplane-flash-browser Manual
Author: <insert document author here>
Abstract: This manual describes what freeplane-flash-browser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freeplane-flash-browser/freeplane-flash-browser.sgml.gz

Format: postscript
Files: /usr/share/doc/freeplane-flash-browser/freeplane-flash-browser.ps.gz

Format: text
Files: /usr/share/doc/freeplane-flash-browser/freeplane-flash-browser.text.gz

Format: HTML
Index: /usr/share/doc/freeplane-flash-browser/html/index.html
Files: /usr/share/doc/freeplane-flash-browser/html/*.html
